language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir -p build
  - cd build
  - cmake -DPRJXRAY_BUILD_TESTING=ON ..
  - make -j 4
  - ctest
